logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO

server:
  servlet:
    session:
      cookie:
        name: UISESSION
spring:
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        provider:
          custom-provider:
            tokenUri: http://localhost:8081/auth/oauth/token
            authorizationUri: http://localhost:8081/auth/oauth/authorize
            userInfoUri: http://localhost:8081/auth/user/me
            userNameAttribute: name